// <auto-generated />
namespace chopper1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MissingdepCode3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MissingdepCode3));
        
        string IMigrationMetadata.Id
        {
            get { return "201702141617214_MissingdepCode3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
