//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chopper1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCBCList4Themes
    {
        public int ID { get; set; }
        public Nullable<short> ChannelCode { get; set; }
        public Nullable<System.DateTime> BCDate { get; set; }
        public Nullable<short> ProducerCode { get; set; }
        public Nullable<short> SellerCode { get; set; }
        public Nullable<byte> BeginHours { get; set; }
        public Nullable<byte> BeginMinutes { get; set; }
        public Nullable<byte> BeginSeconds { get; set; }
        public Nullable<int> BeginTime { get; set; }
        public Nullable<byte> DaysCount { get; set; }
        public byte TimingHours { get; set; }
        public byte TimingMinutes { get; set; }
        public byte TimingSeconds { get; set; }
        public Nullable<int> Timing { get; set; }
        public string Title { get; set; }
        public string Contents { get; set; }
        public string Wildcard { get; set; }
        public string AutorRights { get; set; }
        public Nullable<int> MainID { get; set; }
        public Nullable<System.DateTime> PremiereDate { get; set; }
        public Nullable<bool> Bit_Repetition { get; set; }
        public Nullable<int> TimingFrames { get; set; }
        public Nullable<int> BeginFrames { get; set; }
        public Nullable<double> RR { get; set; }
        public Nullable<double> RM { get; set; }
        public Nullable<double> DR { get; set; }
        public Nullable<double> DM { get; set; }
        public string BeginTimeText { get; set; }
        public string TimingText { get; set; }
        public bool report { get; set; }
        public string PremiereText { get; set; }
        public string CelebrationText { get; set; }
        public string CycleTitle { get; set; }
        public bool archiv { get; set; }
        public bool CelebrationDay { get; set; }
        public Nullable<int> NormedBegin { get; set; }
        public Nullable<double> DSTI { get; set; }
        public int IsForeign { get; set; }
        public string RRstr { get; set; }
        public string RMstr { get; set; }
        public string DRstr { get; set; }
        public string DMstr { get; set; }
        public string DSTIstr { get; set; }
        public Nullable<int> AgeLimit { get; set; }
    }
}
